### ISSUE TITLE
请问complete_analogy_task是如何实现的?

### ISSUE THREAD

**Issue by LiuWenJia-ops** [Yudreamy/GloVe_Chinese_word_embedding#1]
如题

**Comment by YingZhuY** [comment]
Word Analogy Task 词语类比任务 可描述为 `A 对于 B 相当于 C 对于 ?`

具体如 `Paris 对于 France 相当于 Rome 对于 ?`，我们用向量反映语义关系

![word_analogy](https://user-images.githubusercontent.com/53252781/145016448-1855abbb-0e5f-45a4-92f8-cb497ecde6b9.png)

有 **𝐯_{France} − 𝐯_{Paris} ≈ 𝐯_{?} − 𝐯_{Rome}**

即 **𝐯_{?} ≈ 𝐯_{France} - 𝐯_{Paris} + 𝐯_{Rome}**

故 1. 𝐯2−𝐯1+𝐯3 => 𝐯；2. cosine_similarity(𝐯, word_matrix)；3. 排序输出
