### ISSUE TITLE
有一个问题想请教一下，如果是想在这个模型基础之上添加新的语料重新训练需要怎么操作？

### ISSUE THREAD

**Issue by xinjicong** [Yudreamy/GloVe_Chinese_word_embedding#2]
如果是想在这个模型基础之上添加新的语料重新训练需要怎么操作？
是不是要把这个维基语料和新的语料加在一起重新训练才可以？

**Comment by YingZhuY** [comment]
对的，新的语料做一样的 **文本处理** 后，加到维基语料中

比如，类似维基语料，就是从下图左边这样，变成右边这样

![1](https://user-images.githubusercontent.com/53252781/185740629-bff58877-5e2f-485f-a7ad-6b089633f024.PNG)

然后对处理后的文本，用 GloVe 训练词向量即可。

按理说，维基语料挺大的，新的语料越小，对结果的影响可能就越小。

可以试一下
